### ISSUE TITLE
Licensed Server support

### ISSUE THREAD

**Issue by bennetgallein** [Splo0sh/netdata_ts3_plugin#15]
It would be great if this would also support licensed servers, so we can have an overview of the slots we're using & so on.

**Comment by coraxx** [comment]
I will have to check some documentation since I don’t have access to a licensed server.

**Comment by coraxx** [comment]
Is there any specific info available for licensed servers only? Or would you like to see a graph showing the amount of free slots, i.e. `max slots` - `active users` = `free slots`?!

**Comment by bennetgallein** [comment]
Maybe the easiest way would be to query each virtual_server and then add up the `max slots` and the `active users`.. Would be cool if there would be a graph for `total slots` where all the slots added up are displayed, one for `used slots`. I think that would be helpful!
