### ISSUE TITLE
TS3 Plugin not working

### ISSUE THREAD

**Issue by Mystard** [Splo0sh/netdata_ts3_plugin#16]
Getting all sorts of errors with the plugin. Perhaps it's the new server version causing it?

Netdata: v1.10.0-703-gb53f679_rolling
Teamspeak 3 Server: 3.3.0
Python: 2.7.9

I get different errors with different configurations by just changing how I type the host.

This is with my server's full external IP:

> 2018-09-23 11:41:57: python.d ERROR: ts3: local: [Errno 32] Broken pipe used configuration: host: 91.***.***.*** port: 10011 socket: None
> 2018-09-23 11:41:57: python.d ERROR: ts3: local: update() unhandled exception: expected string or buffer
> 2018-09-23 11:41:57: python.d ERROR: ts3: local: stopped after 10 data collection failures in a row

And this happens with both 'localhost' and '127.0.0.1':

> 2018-09-23 11:48:02: python.d ERROR: ts3: local: [Errno 13] Permission denied: '/proc/16076/cmdline'
> 2018-09-23 11:48:02: python.d ERROR: ts3: local: No local TeamSpeak server running. Disabling plugin...
> 2018-09-23 11:48:02: python.d INFO: ts3: local: check() => [FAILED]

**Comment by Mystard** [comment]
Oh, didn't check the code properly.

It appears that Python 3.6.2+ is required?

**Comment by coraxx** [comment]
Hi @Mystard,
sry for the late response, so little time this year ^^

The plugin should work under both python 2 and 3. I will probably have some time on the weekend to update my own installation. Let’s see what problems I encounter then. Maybe something changed.

**Comment by coraxx** [comment]
So I tested my installation both with netdata running locally on the same server and netdata running on an external server. Are you running netdata and teamspeak on the same server?

My Teamspeak server had a problem with the query user so I had to make a new one and update the login info in netdata's `ts3.conf`, but I'm pretty sure that was only a problem with my installation.
After updating netdata and the ts server everything worked fine.

netdata: 1.10.0-752-g07060ae_rolling
teamspeak 3 server: 3.3.0
python: 2.7.3 and 2.7.14

But I encountered a problem when running on the external server. I had to fix the SocketService import. I updated the repo, please try the current version.

If you are still encountering problems, try running the plugin in debug and post the output here.

To run in debug, switch to netdata user:
`sudo su -s /bin/bash netdata`
Run plugin in debug mode:
`/usr/libexec/netdata/plugins.d/python.d.plugin 1 debug trace ts3`

**Comment by Mystard** [comment]
Well I tried with pretty much every combination with both localhost and the full IP.

I also made new query logins just to be sure, grabbed the new version and then decided to also revert the conf back to how it was with just the first login and password lines uncommented, added new logins there and now **it works!**

![ts3](https://puu.sh/BEugK/49ca043803.png)

Thanks for the help!

**Comment by coraxx** [comment]
Glad to hear that it works now :)
