### ISSUE TITLE
ts3_plugin not working after update?

### ISSUE THREAD

**Issue by Raisum** [Splo0sh/netdata_ts3_plugin#9]
Hey, so my TS3_plugin stopped working a week ago. Probably from Netdata update. It connects to the server and gets some data but stops because of some unhandled exception? Here's what happens when I try to debug with: /usr/libexec/netdata/plugins.d/python.d.plugin 1 debug trace ts3

> 2018-02-28 10:50:25: python.d DEBUG: ts3: local: error id=0 msg=ok
> 2018-02-28 10:50:25: python.d ERROR: ts3: local: update() unhandled exception: _receive() takes exactly 1 argument (2 given)
> 2018-02-28 10:50:25: python.d ERROR: ts3: local: stopped after 10 data collection failures in a row
> 2018-02-28 10:50:25: python.d ERROR: ts3: local: Traceback (most recent call last):
>   File "/usr/libexec/netdata/python.d/python_modules/bases/FrameworkServices/SimpleService.py", line 181, in run
>     updated = self.update(interval=job.SINCE_UPDATE)
>   File "/usr/libexec/netdata/python.d/python_modules/bases/FrameworkServices/SimpleService.py", line 207, in update
>     data = self.get_data()
>   File "/usr/libexec/netdata/python.d/python_modules/bases/FrameworkServices/SimpleService.py", line 256, in get_data
>     return self._get_data()
>   File "/usr/libexec/netdata/python.d/ts3.chart.py", line 242, in _get_data
>     raw = self._get_raw_data()
>   File "/usr/libexec/netdata/python.d/python_modules/bases/FrameworkServices/SocketService.py", line 217, in _get_raw_data
>     data = self._receive(raw)
> TypeError: _receive() takes exactly 1 argument (2 given)
> 
> 2018-02-28 10:50:25: python.d INFO: plugin: main: FINISHED

**Comment by coraxx** [comment]
thank you for the debug information! I finally have some time tomorrow to take a look at what's happening here :)

**Comment by coraxx** [comment]
Give it a try, should work again :)

**Comment by Raisum** [comment]
Yeah seems to be working again, thanks!
